DROP DATABASE IF EXISTS  GLOBAL_POLITICS;

CREATE DATABASE GLOBAL_POLITICS;

USE GLOBAL_POLITICS;

CREATE TABLE PUBLICACIONES(
	IMGPATH VARCHAR(100) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(300)
);

CREATE TABLE CARRUSEL(
	IMGPATH VARCHAR(100) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    BUTTONTEXT VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIOS(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    CORREO VARCHAR(150) NOT NULL,
    PSWD VARCHAR(66) NOT NULL,
    ROL VARCHAR(10) CHECK(ROL="ADMIN" OR ROL="NORMAL"),
    ACTIVO INTEGER DEFAULT 1
);

CREATE TABLE ACADEMICOS(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PAIS VARCHAR(50) NOT NULL
);

INSERT INTO USUARIOS(NOMBRES, APELLIDOS, CORREO, PSWD, ROL) VALUES
    ('FULANO1', 'DE TAL1', 'correo1@academicos.com', '#####', 'ADMIN'),
    ('FULANO2', 'DE TAL2', 'correo2@academicos.com', '####*', 'ADMIN'),
    ('FULANO3', 'DE TAL3', 'correo3@academicos.com', '###**', 'NORMAL'),
    ('FULANO4', 'DE TAL4', 'correo4@academicos.com', '##***', 'NORMAL'),
    ('FULANO5', 'DE TAL5', 'correo5@academicos.com', '#****', 'NORMAL');

INSERT INTO ACADEMICOS(NOMBRES, APELLIDOS, TITULO, PAIS, DESCRIPCION) VALUES
    ('Cristóbal', 'Collignon',  'Ph.D.', 'Japón', 'Relaciones y estudios mexicano-japoneses, Diplomacia Pública y Cultural, Teoría Crítica, Teoría de Género y Queer en Relaciones Internacionales, Industrias Creativas.');